### ISSUE TITLE
deleted blocks still keep running

### ISSUE THREAD

**Issue by gengshenghong** [jmoenig/Snap--Build-Your-Own-Blocks#1239]
I've found a confusing issue using snap, reproduce the bug as below:
1. write snap script as below
![image](https://cloud.githubusercontent.com/assets/1018468/15662040/c24069f6-271f-11e6-8947-52cd18b08c73.png)

2. click "green flag" to make it run
3. now, delete the running scripts's block (drag it to the left area)
4. on the stage, the script keeps running, you have to click the "stop button" to stop it. But for children, this is very confusing, the script is empty but the sprite is moving...
Suggestion: the script should stop when a block is running.

Reproduced with the online version snap: http://snap.berkeley.edu/snapsource/snap.html , 4.0.7.2

**Comment by jmoenig** [comment]
good point. I decided on this behavior primarily to speed up primitive loops - especially if they're ```warp```ed. In the meantime we've tweaked performance in many places, so let's find out whether we can do the right thing now. I'll take it on!

**Comment by jmoenig** [comment]
Okay, despite the popular impression that Snap is slow it's hard to remember that it used to be *much* slower in the past. :-)
I've committed a patch that forces the ```forever``` block to re-evaluate the contents of the C-shaped slot at every loop invocation (formerly I cached it), and it works beautifully for me, even with very many ```forever``` loops running in parallel.
Please check out the fixed version in the current development distro:
   http://snap.berkeley.edu/snapsource/dev/snap.html
(Oh, and make sure to flush your cache or to reload Snap until the module ```threads.js``` shows today's date or younger), and let me know if something still doesn't work as expected for you.
Once again thanks for reporting this!

**Comment by jguille2** [comment]
I'm still reproducing the operation reported ("deleted blocks still keep running") in dev distro.

Anyway, I think that fixing it changing ``forever`` behaviour is wrong.  We have many scripts running for a long time without a ``forever`` block. We have *repeat n times*, *repeat until*, *wait until*...

Example:
  > ![snap_example](https://cloud.githubusercontent.com/assets/2926315/15670554/7133756a-2726-11e6-816e-a84eddfaf7f2.png)

  > I can run this script, delete it, and after this, the sprite will turn its color when I clicked space key.

Then, if I want to stop scripts deleted, I must change delete event and stop its script.

Thanks,

Joan

**Comment by jmoenig** [comment]
Ah, I see. Thank you!

So, for me, ```forever``` now behaves the same as ```repeat``` and ```repeat until```, i.e. I can change the contents of the C-shaped slot and it immediately takes effect (on the next iteration). This used not to be the case for ```forever``` (because many projects run zillions of ```forever``` blocks in parallel, and I wanted to cache the script inside the C-slot to boost performance).

A different issue is changing a stack of a protected script section while it is running. Protected sections are "straight" stacks (e.g. inside a loop). They usually run atomically until the next loop iteration or until the end of the script before they yield. This reduces the possibility for race conditions and helps with performance. But - as you've noticed - *timed* (or *interpolated*) blocks such as ```wait```, ```glide``` etc. break the atomicity of protected sections. Scratch 1.4 used to have the same issue executing interpolated operations inside protected sections (check it out!) but has - quite recently, actually - changed this in 2.0. As a longer-term-ish project I'm planning to change Snap's evaluator in many slight ways, and that will also address this issue. However, this will not happen anytime soon.

Can you confirm that changing the inside of a running primitive loop now always immediately takes effect, or did I miss anything?

Thanks!

**Comment by bromagosa** [comment]
I think we're discussing two different issues here.

I confirm that ``forever`` is now working as you describe, but what @jguille2 and @gengshenghong mean is that when you delete a running script, its thread remains alive, which can be a bit confusing to kids. The script is nowhere, but its behaviour is still there.

I guess just adding ``this.activeProcess().stop()`` to ``BlockMorph.prototype.destroy`` would do the trick.

What's cool is we got an extra enhancement for free out of a miss-understanding! :)

p.s. I can send you a PR for this if you want.

**Comment by jguille2** [comment]
Ok!
I think now I undersand :)

And Bernat writes faster than me... :))

I can confirm ``forever`` is now working fine.

Example
  > ![snap_example2](https://cloud.githubusercontent.com/assets/2926315/15673500/5ea50ec0-2737-11e6-97a7-e0e61576f6e5.png)
  > Run this script an then (script is running) put out ``turn`` block. ``Forever`` block continous but it doesn't turn sprite.

Really, ``forever`` it's working ok in dev!!!

Another thing is this issue (about deleting script).  Destroy must stop the script!!

Thanks!!!

Joan

**Comment by jmoenig** [comment]
Haha! Okay, I've just reopened this issue. Now I get it, thanks for the explanations, Bernat and Joan!!
Bernat, if you find an easy and straightforward way to access the stage's thread manager when deleting a block, feel free to issue a pull-request. I haven't yet looked at this in detail (I'm currently working on another part in ```blocks.js```)...

**Comment by bromagosa** [comment]
@jmoenig let me know if you like the solution. Basically I just check whether we're deleting the whole script (that is, if ``this.topBlock() === this``), and stop its ``activeProcess()`` if it is so.

Snap! is already doing the right thing for deleted script parts.

**Comment by jmoenig** [comment]
Wonderful, thanks!

**Comment by jguille2** [comment]
Thanks!
I've tested Bernat solution and it's fine.

Only a comment...

>  Snap! is already doing the right thing for deleted script parts.

Yes, but with the limitations related by Jens. Now ``forever`` refresh its content... but the other threads are not refreshing.
For example, we can return to the description of this issue. Then:
  - If I destroy all the script ( drag ``When green flag clicked``) it will stop (with Bernat addition)-> ok
  - If I destroy the ``turn`` block it will stop (forever refresh its contents) -> ok
  - But if I destroy ``forever`` it will continuous. Because of course script it's still alive.

Anyway, I like these fixes. :+1:  Just writing down current behavior.

Thanks Jens and Bernat,

Joan

**Comment by gengshenghong** [comment]
Thanks, I can confirm the fix works well. Thanks Jens and Bernat.

Shenghong
